micronaut:
  application:
    name: notificationCleanupService

datasources:
  default:
    url: jdbc:postgresql://${POSTGRES_ENDPOINT}/${POSTGRES_DATABASE}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    schema-generate: CREATE
    dialect: POSTGRES
    maximumPoolSize: 1
    allow-pool-suspension: true

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

cleanup:
  expiration-in-days: 30
