micronaut:
  application:
    name: culturalEventsOrganizer
  server:
    port: 8080
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET}"'
        generator:
          refresh-token:
            secret: '"${JWT_GENERATOR_SIGNATURE_SECRET}"'
          access-token:
            expiration: 60

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/cultural_events_organizer_db
    driverClassName: org.postgresql.Driver
    username: db_user
    password: p@SSw0rd
    schema-generate: CREATE_DROP
    dialect: POSTGRES

netty:
  default:
    allocator:
      max-order: 3
