micronaut:
  application:
    name: emailSenderService

email:
  send-from: ${EMAIL_SEND_FROM}

smtp:
  server: ${SMTP_SERVER}
  port: ${SMTP_PORT}
  username: ${SMTP_USERNAME}
  password: ${SMTP_PASSWORD}
