micronaut:
  application:
    name: culturalEventsOrganizer
  server:
    port: 8080
    max-request-size: 1073741824
    multipart:
      max-file-size: 1073741824
  security:
    authentication: bearer
    token:
      jwt:
        bearer:
          prefix: ""
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET}"'
        generator:
          refresh-token:
            secret: '"${JWT_GENERATOR_SIGNATURE_SECRET}"'
    endpoints:
      login:
        path: /api/login
      logout:
        enabled: false
      oauth:
        path: /api/refresh_token

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

datasources:
  default:
    url: jdbc:postgresql://${POSTGRES_ENDPOINT}/${POSTGRES_DATABASE}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    schema-generate: CREATE
    dialect: POSTGRES

aws:
  access-key: ""
  secret-key: ""
  region: "eu-central-1"
  s3:
    bucket-name: "events-media-kjhkjhkjhkjhkjhkjh"

netty:
  default:
    allocator:
      max-order: 3
